
[server]
headless = true
port = "8501"
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#212EDE"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"